version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: travel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: travel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: travel_backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpass
      DB_NAME: travel
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    image: nginx:latest
    container_name: travel_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data:
